version: '3.5'

services:
  todox_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-todox_test}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - todox
    restart: unless-stopped
  todox_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=todox_postgres
    networks:
      - todox
    depends_on:
      - todox_postgres
    restart: unless-stopped

networks:
  todox:
    driver: bridge

volumes:
    postgres:
